import React from "react";
import styles from "./styles.module.css";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "next-1/app/favicon1.ico",
      type: "image/x-icon",
    },
  },
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav>About NavBar</nav>
      <main className={styles.main}>{children}</main>
    </>
  );
}
